---
label: Recipe
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
  hidden: false
- name: permalink
  type: text
  config:
    required: true
  hidden: true
  label: Permalink
  default: recipe
